spring:
  application:
    name: rate-limiting
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60s

rate-limiting:
  profiles:
    strict:
      limit: 5
      duration-seconds: 60
      strategy: INTERVALLY
    standard:
      limit: 20
      duration-seconds: 60
      strategy: GREEDY
    relaxed:
      limit: 100
      duration-seconds: 3600
      strategy: INTERVALLY
