spring:
  application:
    name: idempotent
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 60s

app:
  idempotent:
    timeout-minutes: 10
    result-expire-minutes: 1440
